pipeline {
    agent any

    stages {
        stage('docker build') {
            steps {
                script {
                    sh "docker build -f 02-primer-pipeline/Dockerfile -t pablocblog/homer_page:1.0.0-${BUILD_ID} 02-primer-pipeline"
                }
            }
        }
        stage('docker push') {
            steps {
                script {
                    sh "docker push pablocblog/homer_page:1.0.0-${BUILD_ID}"
                }
            }
        }
          stage('docker run') {
            steps {
                script {
                    sh "ddocker run -it -d -p90${BUILD_ID}:80  pablocblog/homer_page:1.0.0-${BUILD_ID}"
                }
            }
        }
    }
}